name: Repo
description: Создание репозитория
title: '[Repo] '
type: 'Repo'
projects: ["torin-asakura/6"]
assignees:
  - TorinAsakura
body:
  - type: input
    id: repo-name
    attributes:
      label: Название репы
    validations:
      required: true

  - type: textarea
    id: specs
    attributes:
      label: Для чего нужна репа?
    validations:
      required: true
